hey

diff --git a/true-fetch b/true-fetch
--- a/true-fetch
+++ b/true-fetch
@@ -3,7 +3,14 @@
 # Make sure the user cannot escape
 trap '' HUP INT QUIT ILL TRAP ABRT FPE BUS SEGV SYS PIPE ALRM TERM URG CONT CHLD IO XCPU XFSZ VTALRM PROF WINCH USR1 USR2
 clear
-OS=$(fastfetch -s os -l none 2>/dev/null || (uname -a; exit 1));
+OS=$((fastfetch -s os -l none 2>/dev/null) || (sleep 5; uname -a >> /dev/tty; echo "error"));
+if [[ $OS -eq "error" ]]; then
+	SECONDS=0
+	while [[ SECONDS != "8" ]]; do
+		:
+	done
+	exit 1
+fi
 OUTPUT=$(fastfetch --pipe false -s " ")
 LENGTH=$(wc -l <<< "$OUTPUT")
 stty -echo
